-- 코드를 입력하세요
SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE, 'yyyy-mm-dd') AS PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY = '인문' AND
     PUBLISHED_DATE <= TO_DATE('2021-12-31', 'yyyy-mm-dd') AND
     PUBLISHED_DATE >= TO_DATE('2021-01-01', 'yyyy-mm-dd')
ORDER BY PUBLISHED_DATE;